

export const horoscopeArray = [{
    id: 1,
    name: "Kos",
    description: "Energikus, bátor és szenvedélyes.",
    period: "Március 21. - Április 19.",
    image: "https://pixabay.com/hu/images/search/kos/",
},
    {
        id: 2,
        name: "Bika",
        description: "Megbízható, türelmes és praktikus.",
        period: "Április 20. - Május 20.",
        image: "https://hu.pinterest.com/maszatpofa/bika-csillagjegy/",
    },
    {
        id: 3,
        name: "Ikrek",
        description: "Kommunikatív, intelligens és kíváncsi.",
        period: "Május 21. - Június 20.",
        image: "https://depositphotos.com/hu/photos/ikrek.html",
    },
    {
        id: 4,
        name: "Rák",
        description: "Érzékeny, gondoskodó és intuitív.",
        period: "Június 21. - Július 22.",
        image: "https://hu.pinterest.com/madeva7007/csillagjegy-r%C3%A1k/",
    },
    {
        id: 5,
        name: "Oroszlán",
        description: "Magabiztos, kreatív és nagylelkű.",
        period: "Július 23. - Augusztus 22.",
        image: "https://hu.pinterest.com/ildikobacsi/oroszl%C3%A1n/",
    },
    {
        id: 6,
        name: "Szűz",
        description: "Analitikus, precíz és szorgalmas.",
        period: "Augusztus 23. - Szeptember 22.",
        image: "https://www.pinterest.com/pin/547468898434300152/",
    },
    {
        id: 7,
        name: "Mérleg",
        description: "Diplomatikus, igazságos és harmóniára törekvő.",
        period: "Szeptember 23. - Október 22.",
        image: "https://pixabay.com/hu/images/search/m%C3%A9rleg/",
    },
    {
        id: 8,
        name: "Skorpió",
        description: "Szenvedélyes, elszánt és intuitív.",
        period: "Október 23. - November 21.",
        image: "https://pixabay.com/hu/images/search/skorpi%C3%B3/",
    },
    {
        id: 9,
        name: "Nyilas",
        description: "Optimista, kalandvágyó és szabadságszerető.",
        period: "November 22. - December 21.",
        image: "https://pixabay.com/hu/images/search/nyilas/",
    },
    {
        id: 10,
        name: "Bak",
        description: "Ambiciózus, felelősségteljes és kitartó.",
        period: "December 22. - Január 19.",
        image: "https://depositphotos.com/hu/photos/bak.html",
    },
    {
        id: 11,
        name: "Vízöntő",
        description: "Független, eredeti és innovatív.",
        period: "Január 20. - Február 18.",
        image: "https://pixabay.com/hu/images/search/v%C3%ADz%C3%B6nt%C5%91/",
    },
    {
        id: 12,
        name: "Halak",
        description: "Ábrándozó, empatikus és művészi.",
        period: "Február 19. - Március 20.",
        image: "https://pixabay.com/hu/images/search/csillagjegy/",
    },]