export const horoscopeArray = [{
    id: 1,
    name: "Aries",
    description: "Energetic, brave, and passionate.",
    period: "March 21 - April 19",
    image: "",
},
    {
        id: 2,
        name: "Taurus",
        description: "Reliable, patient, and practical.",
        period: "April 20 - May 20",
        image: "",
    },
    {
        id: 3,
        name: "Gemini",
        description: "Communicative, intelligent, and curious.",
        period: "May 21 - June 20",
        image: "",
    },
    {
        id: 4,
        name: "Cancer",
        description: "Sensitive, caring, and intuitive.",
        period: "June 21 - July 22",
        image: "",
    },
    {
        id: 5,
        name: "Leo",
        description: "Confident, creative, and generous.",
        period: "July 23 - August 22",
        image: "",
    },
    {
        id: 6,
        name: "Virgo",
        description: "Analytical, precise, and diligent.",
        period: "August 23 - September 22",
        image: "",
    },
    {
        id: 7,
        name: "Libra",
        description: "Diplomatic, fair, and harmony-seeking.",
        period: "September 23 - October 22",
        image: "",
    },
    {
        id: 8,
        name: "Scorpio",
        description: "Passionate, determined, and intuitive.",
        period: "October 23 - November 21",
        image: "",
    },
    {
        id: 9,
        name: "Sagittarius",
        description: "Optimistic, adventurous, and freedom-loving.",
        period: "November 22 - December 21",
        image: "",
    },
    {
        id: 10,
        name: "Capricorn",
        description: "Ambitious, responsible, and persistent.",
        period: "December 22 - January 19",
        image: "",
    },
    {
        id: 11,
        name: "Aquarius",
        description: "Independent, original, and innovative.",
        period: "January 20 - February 18",
        image: "",
    },
    {
        id: 12,
        name: "Pisces",
        description: "Dreamy, empathetic, and artistic.",
        period: "February 19 - March 20",
        image: "",
    }
];
